lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-h2seq_logo_light.png
    - docs/images/nf-core-h2seq_logo_light.png
    - docs/images/nf-core-h2seq_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-h2seq_logo_light.png
    - docs/images/nf-core-h2seq_logo_light.png
    - docs/images/nf-core-h2seq_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.max_cpus
    - params.max_memory
    - params.max_time
nf_core_version: 3.0.2
repository_type: pipeline
template:
  prefix: charlesfoster
  skip:
    - nf_core_configs
